#Author:Xrafece
server:
  port: 8080
#  servlet:
#    context-path: /one
spring:
  datasource:
    url: jdbc:mysql:///do_sport?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
#mybatis config
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  type-aliases-package: com.xrafece.do_sport.model,com.xrafece.do_sport.dto
  configuration:
    map-underscore-to-camel-case: false